// GENERATED by scripts/GenTables.java from the JDK's Character data (JDK 26.0.2.1). Do not edit.
package io.github.rajumark.hoverfly.hideout.internal

/** Inclusive code point ranges, flattened [start0, end0, start1, end1, ...], base-36 encoded. */
internal object UnicodeTables {
    /** Python str.isspace(): Character.isWhitespace or isSpaceChar, or U+0085: 10 ranges. */
    val SPACE: IntArray = decode(
        "9,d,s,w,3p,3p,4g,4g,4g0,4g0,6bk,6bu,6co,6cp,6cv,6cv,6e7,6e7,9hc,9hc",
    )

    /** Letters and marks (Lu, Ll, Lt, Lm, Lo, Mn, Me, Mc): 751 ranges. */
    val LETTER_OR_MARK: IntArray = decode(
        "1t,2i,2p,3e,4q,4q,51,51,56,56,5c,5y,60,6u,6w,jl,jq,k1,kg,kk,ks,ks,ku,ku,lc,ok,om,on,oq,ot,ov,ov,p2,p" +
        "2,p4,p6,p8,p8,pa,pt,pv,s5,s7,w1,w3,10v,10x,11y,121,121,128,13c,13l,14t,14v,14v,14x,14y,150,151,153,1" +
        "53,15c,162,167,16a,174,17e,17k,19b,19q,1cj,1cl,1cs,1cv,1d4,1d6,1db,1dm,1do,1dr,1dr,1e8,1fu,1fx,1ip,1" +
        "je,1kl,1kq,1kq,1kt,1kt,1kw,1m5,1mo,1nf,1nk,1nu,1o0,1on,1op,1ov,1p3,1r5,1r7,1ur,1v5,1vn,1vp,1vw,1vz,1" +
        "w0,1w3,1wo,1wq,1ww,1wy,1wy,1x2,1x5,1x8,1xg,1xj,1xk,1xn,1xq,1xz,1xz,1y4,1y5,1y7,1yb,1yo,1yp,1z0,1z0,1" +
        "z2,1z2,1z5,1z7,1z9,1ze,1zj,1zk,1zn,208,20a,20g,20i,20j,20l,20m,20o,20p,20s,20s,20u,20y,213,214,217,2" +
        "19,21d,21d,21l,21o,21q,21q,228,22d,22p,22r,22t,231,233,235,237,23s,23u,240,242,243,245,249,24c,24l,2" +
        "4n,24p,24r,24t,24w,24w,25c,25f,261,267,269,26b,26d,26k,26n,26o,26r,27c,27e,27k,27m,27n,27p,27t,27w,2" +
        "84,287,288,28b,28d,28l,28n,28s,28t,28v,28z,29d,29d,29u,29v,29x,2a2,2a6,2a8,2aa,2ad,2ah,2ai,2ak,2ak,2" +
        "am,2an,2ar,2as,2aw,2ay,2b2,2bd,2bi,2bm,2bq,2bs,2bu,2bx,2c0,2c0,2c7,2c7,2dc,2do,2dq,2ds,2du,2eg,2ei,2" +
        "ex,2f0,2f8,2fa,2fc,2fe,2fh,2fp,2fq,2fs,2fu,2fw,2fx,2g0,2g3,2gw,2gz,2h1,2h8,2ha,2hc,2he,2i0,2i2,2ib,2" +
        "id,2ih,2ik,2is,2iu,2iw,2iy,2j1,2j9,2ja,2jg,2ji,2jk,2jn,2k1,2k3,2kg,2ks,2ku,2kw,2ky,2mc,2me,2mg,2mi,2" +
        "mm,2ms,2mv,2n3,2n7,2nu,2nz,2o1,2o3,2o5,2om,2oq,2pd,2pf,2pn,2pp,2pp,2ps,2py,2q2,2q2,2q7,2qc,2qe,2qe,2" +
        "qg,2qn,2r6,2r7,2rl,2t6,2tc,2tq,2v5,2v6,2v8,2v8,2va,2ve,2vg,2w3,2w5,2w5,2w7,2wt,2ww,2x0,2x2,2x2,2x4,2" +
        "xa,2xo,2xr,2yo,2yo,2zc,2zd,305,305,307,307,309,309,30e,30n,30p,31o,31t,32c,32e,32v,32x,33w,346,346,3" +
        "5s,37j,380,39r,3a2,3a5,3a8,3b9,3bb,3bb,3bh,3bh,3bk,3cq,3cs,3m0,3m2,3m5,3m8,3me,3mg,3mg,3mi,3ml,3mo,3" +
        "ns,3nu,3nx,3o0,3ow,3oy,3p1,3p4,3pa,3pc,3pc,3pe,3ph,3pk,3py,3q0,3rk,3rm,3rp,3rs,3tm,3tp,3tr,3uo,3v3,3" +
        "vk,3xx,3y0,3y5,3y9,4fg,4fj,4fz,4g1,4gq,4gw,4iy,4j5,4jc,4jk,4k5,4kf,4l0,4lc,4lv,4m8,4mk,4mm,4mo,4mq,4" +
        "mr,4n4,4pf,4pj,4pj,4po,4pp,4qz,4r1,4r3,4r3,4rk,4u0,4u8,4ve,4vk,4xh,4xs,4ym,4yo,4yz,4z4,4zf,500,50t,5" +
        "0w,510,51c,52j,52o,53d,54w,55n,55s,57i,57k,58c,58f,58f,59j,59j,59s,5b1,5b4,5bf,5c0,5e4,5ez,5f7,5fk,5" +
        "gv,5h6,5ir,5j4,5kn,5l9,5lb,5lm,5ml,5mo,5my,5n4,5oa,5od,5of,5ow,5oy,5p0,5q2,5q8,651,654,659,65c,66d,6" +
        "6g,66l,66o,66v,66x,66x,66z,66z,671,671,673,67x,680,69g,69i,69o,69q,69q,69u,69w,69y,6a4,6a8,6ab,6ae,6" +
        "aj,6ao,6b0,6b6,6b8,6ba,6bg,6ep,6ep,6f3,6f3,6fk,6fw,6hc,6i8,6iq,6iq,6iv,6iv,6iy,6j7,6j9,6j9,6jd,6jh,6" +
        "jo,6jo,6jq,6jq,6js,6js,6ju,6jx,6jz,6k9,6kc,6kf,6kl,6kp,6ku,6ku,6mb,6mc,8ow,8v8,8vf,8vn,8w0,8x1,8x3,8" +
        "x3,8x9,8x9,8xc,8yv,8z3,8z3,8zj,906,90g,90m,90o,90u,90w,912,914,91a,91c,91i,91k,91q,91s,91y,920,926,9" +
        "28,933,94f,94f,9hh,9hi,9ii,9in,9ip,9it,9iz,9j0,9j5,9li,9ll,9lm,9lp,9lr,9lt,9oa,9oc,9of,9ol,9pr,9pt,9" +
        "se,9sw,9tr,9v4,9vj,a9s,fcv,feo,wi4,wk0,wl9,wlc,wss,wsw,wtb,wtm,wtn,wu8,wvm,wvo,wvx,wvz,wyt,wz4,wz5,x" +
        "07,x0f,x0i,x3c,x3f,x5o,x69,x7r,x7w,x7w,x8g,x9v,xa8,xc5,xcw,xdj,xdn,xdn,xdp,xdr,xe2,xf1,xf4,xg3,xgg,x" +
        "h8,xhc,xj4,xjj,xjj,xk0,xkf,xkq,xku,xkw,xme,xmo,xn1,xnk,xo6,xoa,xqa,xqz,xr1,xr4,xrj,xrm,xrq,xs1,xs6,x" +
        "s9,xse,xsh,xsm,xsw,xt2,xt4,xta,xtc,xui,xuk,xux,xv4,xyi,xyk,xyl,xz4,16lf,16ls,16me,16mj,16nv,1d6o,1dg" +
        "t,1dgw,1djt,1dkw,1dl2,1dlf,1dlj,1dlp,1dm0,1dm2,1dme,1dmg,1dmk,1dmm,1dmm,1dmo,1dmp,1dmr,1dms,1dmu,1dp" +
        "t,1dqr,1e0t,1e1c,1e33,1e36,1e4n,1e5s,1e63,1e68,1e6n,1e74,1e7j,1e9c,1e9g,1e9i,1ed8,1ee9,1eey,1ef5,1ef" +
        "u,1eg6,1eim,1eiq,1eiv,1eiy,1ej3,1ej6,1ejb,1eje,1ejg,1ekg,1ekr,1ekt,1eli,1elk,1em2,1em4,1em5,1em7,1em" +
        "l,1emo,1en1,1eo0,1ere,1eyl,1eyl,1f28,1f30,1f34,1f4g,1f4w,1f4w,1f5s,1f6n,1f71,1f7k,1f7m,1f7t,1f80,1f9" +
        "6,1f9c,1fa5,1fa8,1fb7,1fbc,1fbj,1fcw,1fh9,1fhs,1fir,1fiw,1fjv,1fk0,1fl3,1flc,1fmr,1fn4,1fne,1fng,1fn" +
        "u,1fnw,1fo2,1fo4,1fo5,1fo7,1foh,1foj,1fox,1foz,1fp5,1fp7,1fp8,1fpc,1fqr,1fr4,1fzq,1g00,1g0l,1g0w,1g1" +
        "3,1g1s,1g1x,1g1z,1g34,1g36,1g3e,1g5c,1g5h,1g5k,1g5k,1g5m,1g6t,1g6v,1g6w,1g70,1g70,1g73,1g7p,1g80,1g8" +
        "m,1g8w,1g9q,1gbk,1gc2,1gc4,1gc5,1gcg,1gd1,1gdc,1ge1,1ge8,1gex,1gg0,1ghj,1ghq,1ghr,1gjk,1gjn,1gjp,1gj" +
        "q,1gjw,1gk3,1gk5,1gk7,1gk9,1gl1,1gl4,1gl6,1glb,1glb,1gm8,1gn0,1gn4,1gnw,1gow,1gp3,1gp5,1gpy,1gqo,1gs" +
        "5,1gsg,1gt1,1gtc,1gtu,1gu8,1gup,1gxs,1gzs,1h1c,1h2q,1h34,1h4i,1h4w,1h5z,1h6y,1h7p,1h7t,1h7x,1h7z,1h8" +
        "l,1hfk,1hgp,1hgr,1hgs,1hgw,1hgx,1hhe,1hhj,1hiy,1hjw,1hk7,1hk7,1hkg,1hlc,1hm8,1hmt,1ho0,1hok,1hpc,1hp" +
        "y,1hq8,1hs6,1htc,1hth,1htr,1hve,1hvm,1hvm,1hw0,1hwo,1hxc,1hys,1hz8,1hzb,1hzk,1i0j,1i0m,1i0m,1i0w,1i2" +
        "s,1i2x,1i30,1i32,1i33,1i3e,1i3e,1i3g,1i3g,1i4g,1i4x,1i4z,1i5z,1i66,1i69,1i80,1i86,1i88,1i88,1i8a,1i8" +
        "d,1i8f,1i8t,1i8v,1i94,1i9c,1iay,1ibk,1ibn,1ibp,1ibw,1ibz,1ic0,1ic3,1ico,1icq,1icw,1icy,1icz,1id1,1id" +
        "5,1id7,1idg,1idj,1idk,1idn,1idp,1ids,1ids,1idz,1idz,1ie5,1ieb,1iee,1iek,1ieo,1ies,1if4,1ifd,1iff,1if" +
        "f,1ifi,1ifi,1ifk,1igl,1ign,1igw,1igy,1igy,1ih1,1ih1,1ih3,1ih6,1ih8,1ihf,1iht,1ihu,1iio,1ikq,1ila,1il" +
        "d,1im8,1io5,1io7,1io7,1itc,1iut,1iuw,1iv4,1ivs,1ivx,1iww,1iyo,1iys,1iys,1j0g,1j20,1j40,1j4q,1j4t,1j5" +
        "7,1j5s,1j5y,1jb4,1jcq,1jfk,1jhb,1ji7,1jie,1jih,1jih,1jik,1jir,1jit,1jiu,1jiw,1jjp,1jjr,1jjs,1jjv,1jk" +
        "3,1jmo,1jmv,1jmy,1jo7,1joa,1joh,1joj,1jok,1jpc,1jr2,1jrb,1jrb,1jrk,1jtl,1jtp,1jtp,1ju8,1jw8,1jz4,1jz" +
        "b,1k1s,1k2o,1k3k,1k3s,1k3u,1k52,1k54,1k5c,1k6q,1k7j,1k7m,1k87,1k89,1k8m,1kao,1kau,1kaw,1kax,1kaz,1kc" +
        "6,1kca,1kca,1kcc,1kcd,1kcf,1kcn,1kdc,1kdh,1kdj,1kdk,1kdm,1kem,1keo,1kep,1ker,1kew,1kfk,1kgr,1ko0,1ko" +
        "m,1kow,1kpc,1kpe,1kqi,1kqm,1kqq,1kre,1kre,1kts,1kts,1kw0,1lll,1ls0,1lxf,1nyo,1o1c,1o1s,1ovj,1ow0,1ow" +
        "l,1oww,1rzu,1s00,1sg6,1xq8,1xrj,1z40,1zjs,1zk0,1zku,1zlc,1zni,1zo0,1zot,1zow,1zp0,1zpc,1zqu,1zr4,1zr" +
        "7,1zs3,1zsn,1zst,1ztb,205c,206k,20cg,20e7,20f4,20fs,20fv,20gj,20hs,20ju,20jz,20lj,20lr,20m7,20o0,20o" +
        "1,20o3,20o4,20og,20oj,20ow,26dx,26f3,26fy,26io,26lu,2dbk,2dbn,2dbp,2dbv,2dbx,2dby,2dc0,2dk2,2dki,2dk" +
        "i,2dlc,2dle,2dlh,2dlh,2dlw,2dlz,2dm8,2dx7,2fpc,2fsa,2fsg,2fss,2fsw,2ft4,2ftc,2ftl,2ftp,2ftq,2jgg,2jh" +
        "p,2jhs,2jie,2jxh,2jxl,2jxp,2jxu,2jy3,2jya,2jyd,2jyj,2jze,2jzh,2k3m,2k3o,2kg0,2kic,2kie,2kkc,2kke,2kk" +
        "f,2kki,2kki,2kkl,2kkm,2kkp,2kks,2kku,2kl5,2kl7,2kl7,2kl9,2klf,2klh,2kn9,2knb,2kne,2knh,2kno,2knq,2kn" +
        "w,2kny,2kop,2kor,2kou,2kow,2kp0,2kp2,2kp2,2kp6,2kpc,2kpe,2kyt,2kyw,2kzk,2kzm,2l0a,2l0c,2l16,2l18,2l1" +
        "w,2l1y,2l2s,2l2u,2l3i,2l3k,2l4e,2l4g,2l54,2l56,2l60,2l62,2l6q,2l6s,2l6z,2lmo,2lo6,2lob,2lpo,2lpx,2lp" +
        "x,2lqc,2lqc,2lqz,2lr3,2lr5,2lrj,2mm8,2mn2,2mn9,2mne,2mtc,2mti,2mtk,2mu0,2mu3,2mu9,2mub,2muc,2mue,2mu" +
        "i,2muo,2mwd,2mxb,2mxb,2n0g,2n1o,2n1s,2n25,2n2m,2n2m,2nbk,2nce,2ncw,2ne7,2nrk,2nsf,2nyo,2nzk,2o5c,2o6" +
        "6,2o68,2o6t,2o72,2o73,2odc,2odi,2odk,2odn,2odp,2odq,2ods,2oe6,2oe8,2ojo,2ok0,2ok6,2olc,2onf,2pkw,2pk" +
        "z,2pl1,2plr,2plt,2plu,2plw,2plw,2plz,2plz,2pm1,2pma,2pmc,2pmf,2pmh,2pmh,2pmj,2pmj,2pmq,2pmq,2pmv,2pm" +
        "v,2pmx,2pmx,2pmz,2pmz,2pn1,2pn3,2pn5,2pn6,2pn8,2pn8,2pnb,2pnb,2pnd,2pnd,2pnf,2pnf,2pnh,2pnh,2pnj,2pn" +
        "j,2pnl,2pnm,2pno,2pno,2pnr,2pnu,2pnw,2po2,2po4,2po7,2po9,2poc,2poe,2poe,2pog,2pop,2por,2pp7,2ppd,2pp" +
        "f,2pph,2ppl,2ppn,2pq3,2t4w,3q3j,3q4g,3ti5,3ti8,3xyl,3xyo,43q8,43qo,447x,464g,46jh,47pc,4bii,4bio,4i2" +
        "h,jo5c,jobz",
    )

    /** Marks (Mn, Me, Mc): 327 ranges. */
    val MARK: IntArray = decode(
        "lc,of,w3,w9,13l,14t,14v,14v,14x,14y,150,151,153,153,174,17e,18r,19b,19s,19s,1cm,1cs,1cv,1d0,1d3,1d4," +
        "1d6,1d9,1e9,1e9,1f4,1fu,1ie,1io,1kb,1kj,1kt,1kt,1li,1ll,1ln,1lv,1lx,1lz,1m1,1m5,1nd,1nf,1p3,1pb,1qi," +
        "1r5,1r7,1s3,1tm,1to,1tq,1u7,1u9,1uf,1uq,1ur,1vl,1vn,1x8,1x8,1xa,1xg,1xj,1xk,1xn,1xp,1xz,1xz,1ya,1yb," +
        "1z2,1z2,1z5,1z7,20s,20s,20u,20y,213,214,217,219,21d,21d,228,229,22d,22d,22p,22r,24c,24c,24e,24l,24n," +
        "24p,24r,24t,25e,25f,262,267,269,26b,27w,27w,27y,284,287,288,28b,28d,28l,28n,28y,28z,29u,29u,2bi,2bm," +
        "2bq,2bs,2bu,2bx,2c7,2c7,2dc,2dg,2f0,2f0,2f2,2f8,2fa,2fc,2fe,2fh,2fp,2fq,2g2,2g3,2gx,2gz,2ik,2ik,2im," +
        "2is,2iu,2iw,2iy,2j1,2j9,2ja,2jm,2jn,2k3,2k3,2kg,2kj,2m3,2m4,2m6,2mc,2me,2mg,2mi,2ml,2mv,2mv,2n6,2n7," +
        "2o1,2o3,2q2,2q2,2q7,2qc,2qe,2qe,2qg,2qn,2r6,2r7,2sx,2sx,2t0,2t6,2tj,2tq,2wh,2wh,2wk,2ws,2x4,2xa,2zc," +
        "2zd,305,305,307,307,309,309,30e,30f,31t,32c,32e,32f,32l,32v,32x,33w,346,346,36z,37i,386,389,38e,38g," +
        "38i,38k,38n,38t,38x,390,39e,39p,39r,39r,3a2,3a5,3tp,3tr,4k2,4k5,4ky,4l0,4lu,4lv,4mq,4mr,4ok,4pf,4pp," +
        "4pp,4qz,4r1,4r3,4r3,4ud,4ue,4vd,4vd,4yo,4yz,4z4,4zf,55j,55n,579,57i,57k,58c,58f,58f,59s,5b1,5b4,5bf," +
        "5c0,5c4,5dg,5dw,5ez,5f7,5fk,5fm,5gh,5gt,5ie,5ir,5k4,5kn,5ow,5oy,5p0,5pk,5pp,5pp,5pw,5pw,5pz,5q1,5vk," +
        "5xb,6hc,6i8,8vj,8vl,8zj,8zj,928,933,9ii,9in,9ll,9lm,wvj,wvm,wvo,wvx,wwu,wwv,wz4,wz5,x6q,x6q,x6u,x6u," +
        "x6z,x6z,x7n,x7r,x7w,x7w,xa8,xa9,xbo,xc5,xcw,xdd,xdr,xdr,xeu,xf1,xfr,xg3,xhc,xhf,xir,xj4,xk5,xk5,xm1," +
        "xme,xmr,xmr,xn0,xn1,xob,xod,xps,xps,xpu,xpw,xpz,xq0,xq6,xq7,xq9,xq9,xrf,xrj,xrp,xrq,xyb,xyi,xyk,xyl," +
        "1dlq,1dlq,1e68,1e6n,1e74,1e7j,1eyl,1eyl,1f4w,1f4w,1f92,1f96,1gjl,1gjn,1gjp,1gjq,1gjw,1gjz,1gl4,1gl6," +
        "1glb,1glb,1gpx,1gpy,1h5w,1h5z,1h7t,1h7x,1hgr,1hgs,1hiy,1hj3,1hl2,1hlc,1hmq,1hmt,1hq8,1hqa,1hrs,1hs6," +
        "1htc,1htc,1htf,1htg,1htr,1htu,1hv4,1hve,1hvm,1hvm,1hxc,1hxe,1hyf,1hys,1hz9,1hza,1i0j,1i0j,1i0w,1i0y," +
        "1i2b,1i2o,1i2x,1i30,1i32,1i33,1i5o,1i5z,1i66,1i66,1i69,1i69,1ian,1iay,1ibk,1ibn,1id7,1id8,1ida,1idg," +
        "1idj,1idk,1idn,1idp,1idz,1idz,1iea,1ieb,1iee,1iek,1ieo,1ies,1igo,1igw,1igy,1igy,1ih1,1ih1,1ih3,1ih6," +
        "1ih8,1ihc,1ihe,1ihe,1iht,1ihu,1ik5,1ikm,1ila,1ila,1ink,1io3,1iun,1iut,1iuw,1iv4,1ivw,1ivx,1iy8,1iyo," +
        "1j1n,1j1z,1j4t,1j57,1jcc,1jcq,1jjk,1jjp,1jjr,1jjs,1jjv,1jjy,1jk0,1jk0,1jk2,1jk3,1jo1,1jo7,1joa,1jog," +
        "1jok,1jok,1jpd,1jpm,1jqr,1jqx,1jqz,1jr2,1jrb,1jrb,1jrl,1jrv,1jt6,1jtl,1jz4,1jzb,1k4v,1k52,1k54,1k5b," +
        "1k7m,1k87,1k89,1k8m,1kc1,1kc6,1kca,1kca,1kcc,1kcd,1kcf,1kcl,1kcn,1kcn,1kei,1kem,1keo,1kep,1ker,1kev," +
        "1koj,1kom,1kow,1kox,1koz,1koz,1kqc,1kqi,1kqm,1kqq,1kre,1kre,1ow0,1ow0,1ow7,1owl,1xr2,1xrj,1zow,1zp0," +
        "1zqo,1zqu,20jz,20jz,20k1,20lj,20lr,20lu,20o4,20o4,20og,20oh,2ftp,2ftq,2jgg,2jhp,2jhs,2jie,2jxh,2jxl," +
        "2jxp,2jxu,2jy3,2jya,2jyd,2jyj,2jze,2jzh,2k3m,2k3o,2lmo,2lo6,2lob,2lpo,2lpx,2lpx,2lqc,2lqc,2lqz,2lr3," +
        "2lr5,2lrj,2mtc,2mti,2mtk,2mu0,2mu3,2mu9,2mub,2muc,2mue,2mui,2mxb,2mxb,2n1s,2n1y,2nce,2nce,2ne4,2ne7," +
        "2nsc,2nsf,2nzi,2nzj,2o6b,2o6b,2o6e,2o6e,2o6m,2o6n,2o6t,2o6t,2ok0,2ok6,2on8,2one,jo5c,jobz",
    )

    /** Decimal digits (Nd): 72 ranges. */
    val DIGIT: IntArray = decode(
        "1c,1l,19c,19l,1dc,1dl,1j4,1jd,1uu,1v3,1ye,1yn,21y,227,25i,25r,292,29b,2cm,2cv,2g6,2gf,2jq,2jz,2na,2n" +
        "j,2qu,2r3,2ts,2u1,2xc,2xl,2zk,2zt,37k,37t,39s,3a1,4ps,4q1,4r4,4rd,4zq,4zz,53k,53t,58g,58p,58w,595,5e" +
        "8,5eh,5gw,5h5,5kw,5l5,5lc,5ll,wtc,wtl,xcg,xcp,xds,xe1,xjk,xjt,xkg,xkp,xn4,xnd,xyo,xyx,1eds,1ee1,1fhc" +
        ",1fhl,1h68,1h6h,1h6o,1h6x,1ht2,1htb,1hww,1hx5,1hyu,1hz3,1i34,1i3d,1ib4,1ibd,1ikw,1il5,1iog,1iop,1iz4" +
        ",1izd,1j28,1j2h,1j2o,1j37,1j5c,1j5l,1jhc,1jhl,1jkg,1jkp,1k34,1k3d,1k5s,1k61,1kcw,1kd5,1kf4,1kfd,1kgw" +
        ",1kh5,1kr4,1krd,1xrk,1xrt,1zkw,1zl5,1znk,1znt,1zrk,1zrt,206o,206x,2j1s,2j21,2l72,2l8f,2n28,2n2h,2ne8" +
        ",2neh,2nsg,2nsp,2nzl,2nzu,2onk,2ont,2sc0,2sc9",
    )

    /** Character.isUpperCase (Lu plus Other_Uppercase): 660 ranges. */
    val UPPER: IntArray = decode(
        "1t,2i,5c,5y,60,66,74,74,76,76,78,78,7a,7a,7c,7c,7e,7e,7g,7g,7i,7i,7k,7k,7m,7m,7o,7o,7q,7q,7s,7s,7u,7" +
        "u,7w,7w,7y,7y,80,80,82,82,84,84,86,86,88,88,8a,8a,8c,8c,8e,8e,8g,8g,8i,8i,8k,8k,8m,8m,8p,8p,8r,8r,8t" +
        ",8t,8v,8v,8x,8x,8z,8z,91,91,93,93,96,96,98,98,9a,9a,9c,9c,9e,9e,9g,9g,9i,9i,9k,9k,9m,9m,9o,9o,9q,9q," +
        "9s,9s,9u,9u,9w,9w,9y,9y,a0,a0,a2,a2,a4,a4,a6,a6,a8,a8,aa,aa,ac,ac,ae,ae,ag,ah,aj,aj,al,al,ap,aq,as,a" +
        "s,au,av,ax,az,b2,b5,b7,b8,ba,bc,bg,bh,bj,bk,bm,bm,bo,bo,bq,br,bt,bt,bw,bw,by,bz,c1,c3,c5,c5,c7,c8,cc" +
        ",cc,ck,ck,cn,cn,cq,cq,ct,ct,cv,cv,cx,cx,cz,cz,d1,d1,d3,d3,d5,d5,d7,d7,da,da,dc,dc,de,de,dg,dg,di,di," +
        "dk,dk,dm,dm,do,do,dq,dq,dt,dt,dw,dw,dy,e0,e2,e2,e4,e4,e6,e6,e8,e8,ea,ea,ec,ec,ee,ee,eg,eg,ei,ei,ek,e" +
        "k,em,em,eo,eo,eq,eq,es,es,eu,eu,ew,ew,ey,ey,f0,f0,f2,f2,f4,f4,f6,f6,f8,f8,fa,fa,fc,fc,fe,fe,fg,fg,fi" +
        ",fi,fk,fk,fm,fm,fu,fv,fx,fy,g1,g1,g3,g6,g8,g8,ga,ga,gc,gc,ge,ge,og,og,oi,oi,om,om,ov,ov,p2,p2,p4,p6," +
        "p8,p8,pa,pb,pd,pt,pv,q3,r3,r3,r6,r8,rc,rc,re,re,rg,rg,ri,ri,rk,rk,rm,rm,ro,ro,rq,rq,rs,rs,ru,ru,rw,r" +
        "w,ry,ry,s4,s4,s7,s7,s9,sa,sd,tr,v4,v4,v6,v6,v8,v8,va,va,vc,vc,ve,ve,vg,vg,vi,vi,vk,vk,vm,vm,vo,vo,vq" +
        ",vq,vs,vs,vu,vu,vw,vw,vy,vy,w0,w0,wa,wa,wc,wc,we,we,wg,wg,wi,wi,wk,wk,wm,wm,wo,wo,wq,wq,ws,ws,wu,wu," +
        "ww,ww,wy,wy,x0,x0,x2,x2,x4,x4,x6,x6,x8,x8,xa,xa,xc,xc,xe,xe,xg,xg,xi,xi,xk,xk,xm,xm,xo,xo,xq,xq,xs,x" +
        "t,xv,xv,xx,xx,xz,xz,y1,y1,y3,y3,y5,y5,y8,y8,ya,ya,yc,yc,ye,ye,yg,yg,yi,yi,yk,yk,ym,ym,yo,yo,yq,yq,ys" +
        ",ys,yu,yu,yw,yw,yy,yy,z0,z0,z2,z2,z4,z4,z6,z6,z8,z8,za,za,zc,zc,ze,ze,zg,zg,zi,zi,zk,zk,zm,zm,zo,zo," +
        "zq,zq,zs,zs,zu,zu,zw,zw,zy,zy,100,100,102,102,104,104,106,106,108,108,10a,10a,10c,10c,10e,10e,10g,10" +
        "g,10i,10i,10k,10k,10m,10m,10o,10o,10q,10q,10s,10s,10u,10u,10x,11y,3a8,3b9,3bb,3bb,3bh,3bh,3vk,3xx,5m" +
        "x,5mx,5n4,5oa,5od,5of,5xc,5xc,5xe,5xe,5xg,5xg,5xi,5xi,5xk,5xk,5xm,5xm,5xo,5xo,5xq,5xq,5xs,5xs,5xu,5x" +
        "u,5xw,5xw,5xy,5xy,5y0,5y0,5y2,5y2,5y4,5y4,5y6,5y6,5y8,5y8,5ya,5ya,5yc,5yc,5ye,5ye,5yg,5yg,5yi,5yi,5y" +
        "k,5yk,5ym,5ym,5yo,5yo,5yq,5yq,5ys,5ys,5yu,5yu,5yw,5yw,5yy,5yy,5z0,5z0,5z2,5z2,5z4,5z4,5z6,5z6,5z8,5z" +
        "8,5za,5za,5zc,5zc,5ze,5ze,5zg,5zg,5zi,5zi,5zk,5zk,5zm,5zm,5zo,5zo,5zq,5zq,5zs,5zs,5zu,5zu,5zw,5zw,5z" +
        "y,5zy,600,600,602,602,604,604,606,606,608,608,60a,60a,60c,60c,60e,60e,60g,60g,60i,60i,60k,60k,60m,60" +
        "m,60o,60o,60q,60q,60s,60s,60u,60u,60w,60w,60y,60y,610,610,612,612,614,614,616,616,618,618,61a,61a,61" +
        "c,61c,61e,61e,61g,61g,61q,61q,61s,61s,61u,61u,61w,61w,61y,61y,620,620,622,622,624,624,626,626,628,62" +
        "8,62a,62a,62c,62c,62e,62e,62g,62g,62i,62i,62k,62k,62m,62m,62o,62o,62q,62q,62s,62s,62u,62u,62w,62w,62" +
        "y,62y,630,630,632,632,634,634,636,636,638,638,63a,63a,63c,63c,63e,63e,63g,63g,63i,63i,63k,63k,63m,63" +
        "m,63o,63o,63q,63q,63s,63s,63u,63u,63w,63w,63y,63y,640,640,642,642,644,644,646,646,648,648,64a,64a,64" +
        "c,64c,64e,64e,64o,64v,654,659,65k,65r,660,667,66g,66l,66x,66x,66z,66z,671,671,673,673,67c,67j,69k,69" +
        "n,6a0,6a3,6ag,6aj,6aw,6b0,6bc,6bf,6iq,6iq,6iv,6iv,6iz,6j1,6j4,6j6,6j9,6j9,6jd,6jh,6jo,6jo,6jq,6jq,6j" +
        "s,6js,6ju,6jx,6k0,6k3,6ke,6kf,6kl,6kl,6lc,6lr,6mb,6mb,792,79r,8ow,8q7,8rk,8rk,8rm,8ro,8rr,8rr,8rt,8r" +
        "t,8rv,8rv,8rx,8s0,8s2,8s2,8s5,8s5,8se,8sg,8si,8si,8sk,8sk,8sm,8sm,8so,8so,8sq,8sq,8ss,8ss,8su,8su,8s" +
        "w,8sw,8sy,8sy,8t0,8t0,8t2,8t2,8t4,8t4,8t6,8t6,8t8,8t8,8ta,8ta,8tc,8tc,8te,8te,8tg,8tg,8ti,8ti,8tk,8t" +
        "k,8tm,8tm,8to,8to,8tq,8tq,8ts,8ts,8tu,8tu,8tw,8tw,8ty,8ty,8u0,8u0,8u2,8u2,8u4,8u4,8u6,8u6,8u8,8u8,8u" +
        "a,8ua,8uc,8uc,8ue,8ue,8ug,8ug,8ui,8ui,8uk,8uk,8um,8um,8uo,8uo,8uq,8uq,8us,8us,8uu,8uu,8uw,8uw,8uy,8u" +
        "y,8v0,8v0,8v2,8v2,8v4,8v4,8v6,8v6,8vf,8vf,8vh,8vh,8vm,8vm,wu8,wu8,wua,wua,wuc,wuc,wue,wue,wug,wug,wu" +
        "i,wui,wuk,wuk,wum,wum,wuo,wuo,wuq,wuq,wus,wus,wuu,wuu,wuw,wuw,wuy,wuy,wv0,wv0,wv2,wv2,wv4,wv4,wv6,wv" +
        "6,wv8,wv8,wva,wva,wvc,wvc,wve,wve,wvg,wvg,ww0,ww0,ww2,ww2,ww4,ww4,ww6,ww6,ww8,ww8,wwa,wwa,wwc,wwc,ww" +
        "e,wwe,wwg,wwg,wwi,wwi,wwk,wwk,wwm,wwm,wwo,wwo,wwq,wwq,x0i,x0i,x0k,x0k,x0m,x0m,x0o,x0o,x0q,x0q,x0s,x0" +
        "s,x0u,x0u,x0y,x0y,x10,x10,x12,x12,x14,x14,x16,x16,x18,x18,x1a,x1a,x1c,x1c,x1e,x1e,x1g,x1g,x1i,x1i,x1" +
        "k,x1k,x1m,x1m,x1o,x1o,x1q,x1q,x1s,x1s,x1u,x1u,x1w,x1w,x1y,x1y,x20,x20,x22,x22,x24,x24,x26,x26,x28,x2" +
        "8,x2a,x2a,x2c,x2c,x2e,x2e,x2g,x2g,x2i,x2i,x2k,x2k,x2m,x2m,x2x,x2x,x2z,x2z,x31,x32,x34,x34,x36,x36,x3" +
        "8,x38,x3a,x3a,x3f,x3f,x3h,x3h,x3k,x3k,x3m,x3m,x3q,x3q,x3s,x3s,x3u,x3u,x3w,x3w,x3y,x3y,x40,x40,x42,x4" +
        "2,x44,x44,x46,x46,x48,x48,x4a,x4e,x4g,x4k,x4m,x4m,x4o,x4o,x4q,x4q,x4s,x4s,x4u,x4u,x4w,x4w,x4y,x4y,x5" +
        "0,x53,x55,x55,x57,x58,x5a,x5a,x5c,x5c,x5e,x5e,x5g,x5g,x5i,x5i,x5k,x5k,x5m,x5m,x5o,x5o,x6d,x6d,1ee9,1" +
        "eey,1fcw,1fdz,1fhs,1fir,1fn4,1fne,1fng,1fnu,1fnw,1fo2,1fo4,1fo5,1h1c,1h2q,1h74,1h7p,1jfk,1jgf,20cg,2" +
        "0db,20f4,20fs,2kg0,2kgp,2khg,2ki5,2kiw,2kjl,2kkc,2kkc,2kke,2kkf,2kki,2kki,2kkl,2kkm,2kkp,2kks,2kku,2" +
        "kl1,2kls,2kmh,2kn8,2kn9,2knb,2kne,2knh,2kno,2knq,2knw,2koo,2kop,2kor,2kou,2kow,2kp0,2kp2,2kp2,2kp6,2" +
        "kpc,2kq4,2kqt,2krk,2ks9,2kt0,2ktp,2kug,2kv5,2kvw,2kwl,2kxc,2ky1,2kyw,2kzk,2l0i,2l16,2l24,2l2s,2l3q,2" +
        "l4e,2l5c,2l60,2l6y,2l6y,2olc,2om9,2q7k,2q89,2q8g,2q95,2q9c,2qa1",
    )

    private fun decode(s: String): IntArray = s.split(',').map { it.toInt(36) }.toIntArray()

    /** Binary search in a flattened range table. */
    fun contains(table: IntArray, cp: Int): Boolean {
        var lo = 0
        var hi = table.size / 2 - 1
        while (lo <= hi) {
            val mid = (lo + hi) ushr 1
            when {
                cp < table[2 * mid] -> hi = mid - 1
                cp > table[2 * mid + 1] -> lo = mid + 1
                else -> return true
            }
        }
        return false
    }
}
