import java.util.*;
import java.util.function.IntPredicate;

/**
 * Generates UnicodeTables.kt: the character classes Hideout's text rules need, from the JDK's
 * Character data, so every Kotlin platform classifies text exactly like java.util.regex does.
 *
 *   java scripts/GenTables.java > hideout/src/commonMain/kotlin/io/github/rajumark/hoverfly/hideout/internal/UnicodeTables.kt
 */
public class GenTables {
  static boolean letter(int t) {
    return t == Character.UPPERCASE_LETTER || t == Character.LOWERCASE_LETTER || t == Character.TITLECASE_LETTER
        || t == Character.MODIFIER_LETTER || t == Character.OTHER_LETTER;
  }
  static boolean mark(int t) { return t == Character.NON_SPACING_MARK || t == Character.ENCLOSING_MARK || t == Character.COMBINING_SPACING_MARK; }
  static boolean number(int t) { return t == Character.DECIMAL_DIGIT_NUMBER || t == Character.LETTER_NUMBER || t == Character.OTHER_NUMBER; }
  /** [\p{L}\p{N}_] */
  /** Python str.isspace() (as the 1.x library checked it). */
  static boolean space(int cp) { return Character.isWhitespace(cp) || Character.isSpaceChar(cp) || cp == 0x85; }
  /** Character.isLetter. */
  static boolean isLetter(int cp) { return Character.isLetter(cp); }
  static boolean letterOrMarkCp(int cp) { int t = Character.getType(cp); return letter(t) || mark(t); }
  static boolean markCp(int cp) { return mark(Character.getType(cp)); }
  static boolean digit(int cp) { return Character.getType(cp) == Character.DECIMAL_DIGIT_NUMBER; }
  static boolean upper(int cp) { return Character.isUpperCase(cp); }
  static boolean word(int cp) { int t = Character.getType(cp); return cp == '_' || letter(t) || number(t); }
  /** [\p{L}\p{M}] */
  static boolean letterOrMark(int cp) { int t = Character.getType(cp); return letter(t) || mark(t); }

  static List<Integer> ranges(IntPredicate p) {
    List<Integer> r = new ArrayList<>(); int start = -1;
    for (int cp = 0; cp <= 0x110000; cp++) {
      boolean in = cp <= 0x10FFFF && p.test(cp);
      if (in && start < 0) start = cp;
      if (!in && start >= 0) { r.add(start); r.add(cp - 1); start = -1; }
    }
    return r;
  }
  static String enc(List<Integer> r) { StringBuilder sb = new StringBuilder(); for (int v : r) { if (sb.length() > 0) sb.append(','); sb.append(Integer.toString(v, 36)); } return sb.toString(); }
  static void table(StringBuilder o, String doc, String name, List<Integer> r) {
    o.append("    /** ").append(doc).append(": ").append(r.size() / 2).append(" ranges. */\n");
    o.append("    val ").append(name).append(": IntArray = decode(\n");
    String s = enc(r);
    for (int i = 0; i < s.length(); i += 100) o.append("        \"").append(s, i, Math.min(s.length(), i + 100)).append("\" +\n");
    o.setLength(o.length() - 3); o.append(",\n    )\n\n");
  }
  public static void main(String[] a) {
    StringBuilder o = new StringBuilder();
    o.append("// GENERATED by scripts/GenTables.java from the JDK's Character data (JDK ")
     .append(System.getProperty("java.version")).append("). Do not edit.\n");
    o.append("package io.github.rajumark.hoverfly.hideout.internal\n\n");
    o.append("/** Inclusive code point ranges, flattened [start0, end0, start1, end1, ...], base-36 encoded. */\n");
    o.append("internal object UnicodeTables {\n");
    table(o, "Python str.isspace(): Character.isWhitespace or isSpaceChar, or U+0085", "SPACE", ranges(GenTables::space));
    table(o, "Letters and marks (Lu, Ll, Lt, Lm, Lo, Mn, Me, Mc)", "LETTER_OR_MARK", ranges(GenTables::letterOrMarkCp));
    table(o, "Marks (Mn, Me, Mc)", "MARK", ranges(GenTables::markCp));
    table(o, "Decimal digits (Nd)", "DIGIT", ranges(GenTables::digit));
    table(o, "Character.isUpperCase (Lu plus Other_Uppercase)", "UPPER", ranges(GenTables::upper));
    o.append("    private fun decode(s: String): IntArray = s.split(',').map { it.toInt(36) }.toIntArray()\n\n");
    o.append("    /** Binary search in a flattened range table. */\n");
    o.append("    fun contains(table: IntArray, cp: Int): Boolean {\n");
    o.append("        var lo = 0\n        var hi = table.size / 2 - 1\n");
    o.append("        while (lo <= hi) {\n            val mid = (lo + hi) ushr 1\n");
    o.append("            when {\n                cp < table[2 * mid] -> hi = mid - 1\n                cp > table[2 * mid + 1] -> lo = mid + 1\n                else -> return true\n            }\n        }\n        return false\n    }\n}\n");
    System.out.print(o);
  }
}
